SELECT 
	MATERIAL.Nombre_Material,
	PROVEEDOR.Nombre_Proveedor
FROM PROVEEDOR_MATERIAL
LEFT JOIN PROVEEDOR
ON PROVEEDOR_MATERIAL.ID_Proveedor=PROVEEDOR.ID_Proveedor
LEFT JOIN MATERIAL
ON PROVEEDOR_MATERIAL.ID_Material=MATERIAL.ID_Material;

